# This is a basic workflow to help you get started with Actions

name: build-static

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0

      - name: install myst
        run: npm install -g myst-cli
        
      - name: build with myst
        run: myst build paper.md
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: paper.tex
          working_directory: _build/exports/paper_tex
        
      - name: move paper.pdf up
        run: mv _build/exports/paper_tex/paper.pdf _build/exports/paper.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: output-files
          path: _build/exports/
